Bug fix: Polling status using POST-as-GET wherever possible
therootcompany/acme.js pull request #1
Opened 2021-04-28 13:40 UTC by sam-lord

Avoid repeating finalize POST request and challenge POST requests by
using POST-as-GET requests instead. Allows for testing with Pebble,
and more correctly follows the spec.

2021-04-28 16:58 UTC, coolaj86 requested changes
Definitely don't want to make requests insecure by default.

The other changes look reasonable. Assuming that you've tested them against Let's Encrypt as well as pebble, these seem fine to me.

2021-04-28 16:58 UTC, coolaj86 commented on lib/native.js
> +	rejectUnauthorized: false
This should be an option or environment variable. The default behavior should not be to allow unsigned, expired, and/or unverifiable certificates.

2021-04-28 16:58 UTC, coolaj86 commented on lib/native.js
> +		agent: http01Agent
Monkey patching `native._http01` in cases where an insecure agent is required would also be acceptable.

2021-04-28 17:02 UTC, sam-lord commented
My bad, those changes were not meant for this PR - I was planning on tidying those up once I'd tested that it works for my use case. I'm going to clear those changes from this PR and just leave the original. I'll bring up the http-01 over HTTPS separately

2021-04-29 17:07 UTC, sam-lord commented
Reverted the changes mentioned, they were not meant for this PR and were part of some internal testing I was doing :)

We have tested the original changes for this PR for over a week against real LetsEncrypt *and* Pebble.

2021-04-29 23:59 UTC, coolaj86 approved these changes
LGTM

2021-04-30 00:00 UTC, coolaj86 commented
Rebase / Merge at will.

2021-05-24 10:01 UTC, merged